// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package smbconnector.actions;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.lang.Iterable;
import java.util.List;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class createTestFile extends CustomJavaAction<IMendixObject>
{
	public createTestFile(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		InputStream inputStream = new ByteArrayInputStream("This is a test file.".getBytes());
		IMendixObject obj = Core.instantiate(getContext(), "System.FileDocument");
		Core.storeFileDocumentContent(getContext(), obj, inputStream);
		inputStream.close();
		return obj;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "createTestFile";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
