// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package smbconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import jcifs.smb.SmbFileInputStream;
import com.hierynomus.smbj.SMBClient;
import com.hierynomus.smbj.SmbConfig;
import com.hierynomus.smbj.auth.AuthenticationContext;
import com.hierynomus.smbj.connection.Connection;
import com.hierynomus.smbj.session.Session;
import com.hierynomus.smbj.share.DiskShare;
import java.io.InputStream;
import java.util.concurrent.TimeUnit;
import org.apache.commons.io.IOUtils;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.core.conf.RuntimeVersion;
import com.mendix.core.objectmanagement.member.MendixBoolean;
import com.mendix.integration.WebserviceException;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.ISession;
import com.mendix.systemwideinterfaces.core.IUser;

public class readFile extends CustomJavaAction<IMendixObject>
{
	private java.lang.String smbpath;
	private java.lang.String user;
	private java.lang.String password;

	public readFile(IContext context, java.lang.String smbpath, java.lang.String user, java.lang.String password)
	{
		super(context);
		this.smbpath = smbpath;
		this.user = user;
		this.password = password;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
    	Core.getLogger("SmbUtil").info("read start");

		SmbFileInputStream sfis = null;
		IMendixObject obj = Core.instantiate(getContext(), "System.FileDocument");
		try {
			jcifs.Config.setProperty("jcifs.smb.client.username", user);
			jcifs.Config.setProperty("jcifs.smb.client.password", password);
			sfis = new SmbFileInputStream( smbpath );
			Core.storeFileDocumentContent(getContext(), obj, sfis);
		} catch (Exception e) {
        	Core.getLogger("SmbUtil").error("Couldn't read File");
		} finally {
			if (sfis != null) {
				sfis.close();
			}
		}
    	Core.getLogger("SmbUtil").info("read end");
        return obj;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "readFile";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
