// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package smbconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import jcifs.smb.SmbFileOutputStream;
import com.hierynomus.smbj.SMBClient;
import com.hierynomus.smbj.SmbConfig;
import com.hierynomus.smbj.auth.AuthenticationContext;
import com.hierynomus.smbj.connection.Connection;
import com.hierynomus.smbj.session.Session;
import com.hierynomus.smbj.share.DiskShare;
import java.io.InputStream;
import java.util.concurrent.TimeUnit;
import org.apache.commons.io.IOUtils;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.core.conf.RuntimeVersion;
import com.mendix.core.objectmanagement.member.MendixBoolean;
import com.mendix.integration.WebserviceException;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.ISession;
import com.mendix.systemwideinterfaces.core.IUser;

public class saveFile extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __file;
	private system.proxies.FileDocument file;
	private java.lang.String smbpath;
	private java.lang.String user;
	private java.lang.String password;

	public saveFile(IContext context, IMendixObject file, java.lang.String smbpath, java.lang.String user, java.lang.String password)
	{
		super(context);
		this.__file = file;
		this.smbpath = smbpath;
		this.user = user;
		this.password = password;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.file = __file == null ? null : system.proxies.FileDocument.initialize(getContext(), __file);

		// BEGIN USER CODE
//		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
    	Core.getLogger("SmbUtil").info("save start" + file.getGUID());
		if (!file.getHasContents()) {
			return false;
		}

		boolean ret = false;
		SmbFileOutputStream sfos = null;
		try {
			jcifs.Config.setProperty("jcifs.smb.client.username", user);
			jcifs.Config.setProperty("jcifs.smb.client.password", password);
			sfos = new SmbFileOutputStream( smbpath, false );

    		Core.getLogger("SmbUtil").info("write" + file.getGUID());
//			fileDocument.getContents(getContext(), sfos);
    		InputStream inputStream = Core.getFileDocumentContent(getContext(), file.getMendixObject());
			IOUtils.copy(inputStream, sfos);
			ret = true;
		} catch (Exception e) {
        	Core.getLogger("SmbUtil").error("Couldn't save FileDocument '" + file.getGUID());
		} finally {
			if (sfos != null) {
				sfos.close();
			}
		}
    	Core.getLogger("SmbUtil").info("save end" + file.getGUID());
        return ret;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "saveFile";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
